### ISSUE TITLE
Possibility of using semantic release ?

### ISSUE THREAD

**Issue by dipeshwalia** [b-yond-infinite-network/jest-cucumber-fusion#1]
**Describe the feature you'd like:**

I would like to add semantic release (the way we are using for [infinity-ui-lib](https://github.com/b-yond-infinite-network/infinity-ui-lib/releases). So the process for generating releases, change log is fully automated. 

If this is something that you think will work, i can do a PR.

**Comment by bruno-morel** [comment]
of course, this should be already be the case, did I miss something? :)

**Comment by dipeshwalia** [comment]
oops i don't have permission to write to this git repo. I did a little demo to showcase what i meant but couldn't do git push (for a new branch.)

**Comment by dipeshwalia** [comment]
Like we discus, here are the following properties in package.json to automate release . 
### dev dependencies 
```json   
"commitizen": "^4.0.3",
"cz-conventional-changelog": "^3.1.0",
"semantic-release": "^17.0.2",
```

### npm scripts
```json   
"commit": "git-cz"
"semantic-release": "semantic-release",
```

### other configuration
```json
"version": "0.0.0-semantically-released",
"private": false,
"repository": {
    "type": "git",
    "url": "https:git@github.com:b-yond-infinite-network/NAME_OF_REPO.git"
},
"publishConfig": {
    "access": "public"
},
"config": {
    "commitizen": {
        "path": "./node_modules/cz-conventional-changelog"
    }
},
"release": {
    "plugins": [
        "@semantic-release/commit-analyzer",
        "@semantic-release/release-notes-generator",
        [
            "@semantic-release/npm",
            {
                "npmPublish": true,
                "pkgRoot": "build"
            }
        ]
    ],
    "parserOpts": {
        "mergePattern": "Merged PR .*:"
    }
},
```
### to Commit 
```js
npm run commit // as compare to git commit. 
```
### travis deploy script (usually trigger via merge to master)

```bash
rm -f ~/.npmrc
touch ~/.npmrc
echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc

( npm run semantic-release)
```
[example build https://travis-ci.com/b-yond-infinite-network/infinity-ui-lib/builds/146820775#L715]
[Note: NPM_TOKEN is set in travis settings]
