### ISSUE TITLE
[Question] Multiple scenarios

### ISSUE THREAD

**Issue by godrose** [b-yond-infinite-network/jest-cucumber-fusion#11]
First of all, nice stuff. I've been using BDD and cucumber for 5 years now and am a huge fan of the approach.

So, do you support multi-scenario feature files? if yes, what's the syntax?
Thanks.

**Comment by bruno-morel** [comment]
You mean like this? Or you mean multiple features in the same feature file?
`Feature: Online sales

    Scenario Outline: Selling an <Item>
        Given I have a(n) <Item>
        When I sell the <Item>
        Then I should get $<Amount>

        Examples:

        | Item                                           | Amount |
        | Autographed Neil deGrasse Tyson book           | 100    |
        | Rick Astley t-shirt                            | 22     |
        | An idea to replace EVERYTHING with blockchains | 0      |

    Scenario: Selling a thing
        Given I have an Item named '<ThatCouldLookLikeAnOutlineVariable>'
        When I sell <ThatCouldLookLikeAnOutlineVariable With Spaces in it>
        Then I get $<Amount>`
