### ISSUE TITLE
language support

### ISSUE THREAD

**Issue by stevensnoeijen** [b-yond-infinite-network/jest-cucumber-fusion#15]
I'm trying to add tests in another language (than english) but this doesn't work.
I dived in this problem and came to the conclusion that this should be fixed in jest-cucumber:  https://github.com/bencompton/jest-cucumber/issues/107

Any thoughts?

**Comment by bruno-morel** [comment]
That would be great indeed. Can you give example of what your trying to achieve so that we can write test to be ready when jest-cucumber supports it?

**Comment by stevensnoeijen** [comment]
Sorry, didnt see your comment. Ill pick this up very soon!

**Comment by tetrox** [comment]
@stevensnoeijen I thik we need trow lang code from jest-cucumber.
if we up version at 3.0.1, jest-cucumber will return correctly steps, but don't know lang code.

**Comment by stevensnoeijen** [comment]
If we use 3.0.1 language would also be supported 😛. I'll look into a PR this weekend

**Comment by stevensnoeijen** [comment]
working on it: https://github.com/stevensnoeijen/jest-cucumber-fusion/tree/upgrade_jest-cucumber_to_v3

**Comment by stevensnoeijen** [comment]
There is an issue in the language support for jest-cucumber, i'll be fixing that first before continuing on this

**Comment by stevensnoeijen** [comment]
I created a PR on jest-cucumber that should fix the issue I'm facing with my current test, some steps weren't correctly translated due to an error in the translation.

**Comment by stevensnoeijen** [comment]
PR in jest-cucumber is merged and i'll continue on this after there is a new releases for jest-cucumber.

**Comment by bruno-morel** [comment]
excellent. need any help other than reviewing it when you're ready with the code?

**Comment by stevensnoeijen** [comment]
nope, dev on jest-cucumber is going well, so hopefully we can add this feature soon :)

**Comment by stevensnoeijen** [comment]
created a PR;https://github.com/b-yond-infinite-network/jest-cucumber-fusion/pull/22 .
I did it anyway because waiting on a new release from jest-cucumber might take longer than I thought. And this should work anyways (excluding some language bugs, you can read about them at https://github.com/bencompton/jest-cucumber/pull/123).

**Comment by stevensnoeijen** [comment]
added in v0.8.0
