### ISSUE TITLE
Add support for jest-cucumber 3.0.0

### ISSUE THREAD

**Issue by jonavon** [b-yond-infinite-network/jest-cucumber-fusion#21]
jest-cucumber 2.0.0 does not support updated Gherkin syntax

Including [Rule](https://cucumber.io/docs/gherkin/reference/#rule)
```
Error parsing feature Gherkin: Parser errors:
    (34:5): expected: #EOF, #TableRow, #DocStringSeparator, #StepLine, #TagLine, #ScenarioLine, #ScenarioOutlineLine, #Comment, #Empty, got 'Rule: User must authenticate'
```

**Comment by stevensnoeijen** [comment]
3.0.1 please for supporting of languages too :smile:

**Comment by bruno-morel** [comment]
Nice, didn't see Cucumber had released 3.x. I'll check the upgrade.

**Comment by tetrox** [comment]
bump!
need lang-support to.

@stevensnoeijen , thank you. Your changes in jest-cucumber 3.0.1 is so helpfull.

**Comment by stevensnoeijen** [comment]
https://github.com/b-yond-infinite-network/jest-cucumber-fusion/pull/22
